### ISSUE TITLE
Feature request: add browser build

### ISSUE THREAD

**Issue by fimion** [antfu/vue-global-api#1]
Ideally, make a browser version that works with the iife version of `vue-demi` for codepen magic?

**Comment by antfu** [comment]
Actually in CDN, you could have the API global by simply

```ts
Object.assign(window, Vue)
```

**Comment by fimion** [comment]
![Oh Right... Right.](https://media.giphy.com/media/QvG6xgI4tcOeK293M7/giphy-downsized.gif)

**Comment by antfu** [comment]
Mentioned in README
