### ISSUE TITLE
Uncaught ReferenceError: ref is not defined

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [antfu/vue-global-api#11]
Hi. 

When used within SFC works great.
When used outside SFC, get these `Uncaught ReferenceError`

Example: [gist](https://gist.githubusercontent.com/CharlesOkwuagwu/d91fabd0bba5879882d7dfe26eb5b28c/raw/ec27fc388d25b50d1adb4cc58a5198084b691e80/useStore.ts)

adding `import { xxx } from 'vue'` fixes them, but this defeated the purpose of  `vue-global-api`

**Comment by antfu** [comment]
Does `vue-global-api` been imported before your file entry?

**Comment by CharlesOkwuagwu** [comment]
vue-global-api is imported in main.ts, before mounting the App.

Does the order of import statements in main.ts matter?

```ts
import { createApp } from 'vue'
import { createRouter, createWebHistory } from 'vue-router'
import routes from 'virtual:generated-pages'
import App from './App.vue'
import './assets/css/main.css'
import 'virtual:windi.css'
import 'virtual:windi-devtools'
import 'vue-global-api'

const router = createRouter({
  history: createWebHistory(),
  routes
})

const app = createApp(App)

app.use(router)
app.mount('#app')
```

**Comment by antfu** [comment]
Yes, have you tried?

**Comment by CharlesOkwuagwu** [comment]
ah, I see!

this works now, Thanks!

```ts
import { createApp } from 'vue'
import 'vue-global-api'
import { createRouter, createWebHistory } from 'vue-router'
import routes from 'virtual:generated-pages'
import App from './App.vue'
import './assets/css/main.css'
import 'virtual:windi.css'
import 'virtual:windi-devtools'

const router = createRouter({
  history: createWebHistory(),
  routes
})

const app = createApp(App)

app.use(router)
app.mount('#app')
```

**Comment by CharlesOkwuagwu** [comment]
Do we need to mention the import order in the readme?
