### ISSUE TITLE
How to use with jest?

### ISSUE THREAD

**Issue by natemate90** [antfu/vue-global-api#15]
Hi, can you add an example on how to use vue-global-api in jest?

**Comment by antfu** [comment]
Doesn't it just work?

**Comment by natemate90** [comment]
No, for example, I get 

`    ReferenceError: computed is not defined`

whereas I have defined it in main.ts

**Comment by antfu** [comment]
if you import it in your `*.test.js`?

**Comment by natemate90** [comment]
Indeed, it works when importing the entire package on top of the test file:

`import 'vue-global-api'`
