### ISSUE TITLE
Nuxt usage

### ISSUE THREAD

**Issue by mirabledictu** [antfu/vue-global-api#20]
Hi, feel free to close this anytime.

Is there a best way of importing this in a Nuxt project?

First thing I did is to create a `vue-global-api.ts` file inside my `plugins` directory and import it in `plugins` in `nuxt.config.ts`. The types are working but when you run it, you'll still get undefined errors.

Second thing I did, which worked, is to just import `vue-global-api` in each of the layout component inside `layouts` folder.

Just wondering if there's a better way of doing this. Thanks!

**Comment by antfu** [comment]
Consider using https://github.com/antfu/unplugin-auto-import which has first-class nuxt module built-in

**Comment by wobsoriano** [comment]
I tried `unplugin-auto-import` with nuxt

```javascript
buildModules: [
  '@nuxt/typescript-build',
  '@nuxtjs/composition-api/module',
  'nuxt-typed-vuex',
  [
    'unplugin-auto-import/nuxt',
    {
      // global imports to register
      // imports: ['vue2']
      imports: [
        {
          '@nuxtjs/composition-api': CommonCompositionAPI,
        },
      ],
    },
  ],
],
```

Preset `vue2` and custom preset still gives cannot find name 'defineComponent' etc..

![Screen Shot 2021-08-24 at 6 12 21 PM](https://user-images.githubusercontent.com/13049130/130599213-5cbbe09a-db38-4d1e-a499-56f0c6c9f88c.png)

Also tried restarting vs code with no luck
